services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: shopify-app

    working_dir: /var/www/html

    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest

    container_name: shopify-nginx

    ports:
      - "8000:80"

    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  mysql:
    image: mysql:8.4

    container_name: shopify-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopify_app
      MYSQL_USER: shopify
      MYSQL_PASSWORD: shopify

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: